<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8"/>
        <title>User Control List</title>
        <link rel="stylesheet" href="app/css/usercontrol.css" type="text/css" media="screen" />
    </head>
    <body>
        <header id="header">
            <hgroup>
                <h2 class="section_title">User Control</h2>
            </hgroup>
        </header>
        <aside id="sidebar" class="column">
            <h3>Administración</h3>
            <ul class="toggle">
                <li class="icn_add_user"><a href="#">Nuevo Usuario</a></li>
                <li class="icn_view_users"><a href="#">Ver Usuarios</a></li>
            </ul>
        </aside>
        <section id="main" class="column">
            <article>
                <div>
                    <div style="margin:5% 0 0 2%;">
                        <table class="tablesorter">
                            <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>e-mail</th>
                                <th>Login</th>
                                <th>Dirección</th>
                                <th>Fecha Creación</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            foreach ($userInfo as $usr) {
                                echo "<tr><td>".$usr["nameUser"]."</td>";
                                echo "<td>".$usr["emailUser"]."</td>";
                                echo "<td>".$usr["loginUser"]."</td>";
                                echo "<td>".$usr["addressUser"]."</td>";
                                echo "<td>".$usr["dateCreateUser"]."</td></tr>";
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </article>
            <div class="clear"></div>
        </section>
    </body>
</html>
